import React from "react";
import styles from "./layout.module.css";
import Head from "next/head";
import SideBar from "./sideBar/SideBar";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? `${title}-Portfolio` : "Portfolio"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <SideBar />
        {children}
      </main>
      <footer>All Rights Reserved</footer>
    </>
  );
};

export default Layout;
